import { MigrationInterface, QueryRunner } from "typeorm";

export class Autogenerated1697668817920 implements MigrationInterface {
    name = 'Autogenerated1697668817920'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`attachment\` (\`path\` varchar(255) NOT NULL, \`filename\` varchar(255) NOT NULL, \`newsId\` int NULL, PRIMARY KEY (\`path\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`news\` (\`id\` int NOT NULL AUTO_INCREMENT, \`subject\` varchar(255) NOT NULL, \`content\` longtext NOT NULL, \`scheduled\` datetime NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`extraRecipients\` text NOT NULL DEFAULT '', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`subscription\` (\`email\` varchar(320) NOT NULL, \`name\` varchar(120) NULL, PRIMARY KEY (\`email\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`category\` (\`name\` varchar(30) NOT NULL, \`deletedAt\` datetime(6) NULL, PRIMARY KEY (\`name\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`news_categories_category\` (\`newsId\` int NOT NULL, \`categoryName\` varchar(30) NOT NULL, INDEX \`IDX_d2f307c6f288fb4036451f66b4\` (\`newsId\`), INDEX \`IDX_62062916283839e9fcc3e3f66c\` (\`categoryName\`), PRIMARY KEY (\`newsId\`, \`categoryName\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`subscription_categories_category\` (\`subscriptionEmail\` varchar(320) NOT NULL, \`categoryName\` varchar(30) NOT NULL, INDEX \`IDX_ba5a4882f77b750587fa259736\` (\`subscriptionEmail\`), INDEX \`IDX_85ec6710deff092ed991e431aa\` (\`categoryName\`), PRIMARY KEY (\`subscriptionEmail\`, \`categoryName\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`attachment\` ADD CONSTRAINT \`FK_acbfbec0fcba787deb589cd2a22\` FOREIGN KEY (\`newsId\`) REFERENCES \`news\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`news_categories_category\` ADD CONSTRAINT \`FK_d2f307c6f288fb4036451f66b4d\` FOREIGN KEY (\`newsId\`) REFERENCES \`news\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`news_categories_category\` ADD CONSTRAINT \`FK_62062916283839e9fcc3e3f66c3\` FOREIGN KEY (\`categoryName\`) REFERENCES \`category\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`subscription_categories_category\` ADD CONSTRAINT \`FK_ba5a4882f77b750587fa259736c\` FOREIGN KEY (\`subscriptionEmail\`) REFERENCES \`subscription\`(\`email\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`subscription_categories_category\` ADD CONSTRAINT \`FK_85ec6710deff092ed991e431aa4\` FOREIGN KEY (\`categoryName\`) REFERENCES \`category\`(\`name\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`subscription_categories_category\` DROP FOREIGN KEY \`FK_85ec6710deff092ed991e431aa4\``);
        await queryRunner.query(`ALTER TABLE \`subscription_categories_category\` DROP FOREIGN KEY \`FK_ba5a4882f77b750587fa259736c\``);
        await queryRunner.query(`ALTER TABLE \`news_categories_category\` DROP FOREIGN KEY \`FK_62062916283839e9fcc3e3f66c3\``);
        await queryRunner.query(`ALTER TABLE \`news_categories_category\` DROP FOREIGN KEY \`FK_d2f307c6f288fb4036451f66b4d\``);
        await queryRunner.query(`ALTER TABLE \`attachment\` DROP FOREIGN KEY \`FK_acbfbec0fcba787deb589cd2a22\``);
        await queryRunner.query(`DROP INDEX \`IDX_85ec6710deff092ed991e431aa\` ON \`subscription_categories_category\``);
        await queryRunner.query(`DROP INDEX \`IDX_ba5a4882f77b750587fa259736\` ON \`subscription_categories_category\``);
        await queryRunner.query(`DROP TABLE \`subscription_categories_category\``);
        await queryRunner.query(`DROP INDEX \`IDX_62062916283839e9fcc3e3f66c\` ON \`news_categories_category\``);
        await queryRunner.query(`DROP INDEX \`IDX_d2f307c6f288fb4036451f66b4\` ON \`news_categories_category\``);
        await queryRunner.query(`DROP TABLE \`news_categories_category\``);
        await queryRunner.query(`DROP TABLE \`category\``);
        await queryRunner.query(`DROP TABLE \`subscription\``);
        await queryRunner.query(`DROP TABLE \`news\``);
        await queryRunner.query(`DROP TABLE \`attachment\``);
    }

}
